// lang.js
export const translations = {
  jp: {
    aboutTitle: "マケイ",
    aboutText:
      "東京在住のバイリンガルWeb開発者。スマートで構造的、かつクリエイティブなWeb体験を創り上げます。",
    projectsTitle: "実績",
    project1Title: "サイトリニューアル",
    project1Desc: "PMとして2件の大規模サイトリニューアルを担当。構造もサーバー環境も異なる2サイトをゼロから再構築し、設計から公開までを主導。（使用技術：WordPress／PHP／HTML／CSS／JavaScript／Kinsta／MySQL（MariaDB）／HubSpot（フォーム・チャットボット機能のみ）／AWS（CloudFront Functions・Route 53））",
    project2Title: "Web制作",
    project2Desc: "地方自治体から小規模企業まで、5年以上にわたり個人クライアント向けにサイト制作から保守管理までを一貫して担当（使用技術：HTML／CSS／JavaScript／React／TypeScript／Next.js）",
    project3Title: "既存サイトの運用・保守・UX改善",
    project3Desc: "WordPress、HubSpot、STUDIOなど複数のCMSにおいて、運用・保守業務を担当。バグ修正、機能追加、サーバー対応、更新手順などの技術ドキュメント作成まで幅広く対応。",
    contactText: "東京都",
    skillsTitle: "スキル",
    skill1Title: "フロントエンド",
    skill1Item1: "HTML / CSS / JavaScript（6年）　",
    skill1Item2: "React / TypeScript / Next.js（1年）",
    skill1Item3: "Cypress（E2Eテスト）",
    skill2Title: "バックエンド",
    skill2Item1: "Ruby（1年）",
    skill2Item2: "データベース操作（MySQL / MariaDB）",
    skill2Item3: "API連携・実装",
    skill3Title: "SRE / インフラ",
    skill3Item1: "DNS設計・管理",
    skill3Item2: "サーバー構成・運用",
    skill3Item3: "Cloud Functions（自動化処理）",
    skill3Link: "https://sivasq.siva-s.com/posts/the-best-challenger",
    passionTitle: "パッションプロジェクト",
    passionText: "特別支援教育に携わるボランティアを始めて約10年。これまでに日本全国10校以上で、1,000人を超える子どもたちへの指導や教材作成を行ってきました。現在は、オリジナルの絵本をもとに、多様な学習ニーズに対応したインタラクティブなウェブサイトを開発しています。",
  },
  en: {
    aboutTitle: "McK",
    aboutText:
      "Bilingual Web Developer based in Tokyo, Japan",
    projectsTitle: "Experience",
    project1Title: "Large-Scale Site Renewals",
    project1Desc: "Led two major website renewals for a high-profile SaaS company. Rebuilt both sites from scratch with different structures and server setups, managing everything from planning to launch (Tech stack: WordPress, PHP, HTML, CSS, JavaScript, Kinsta, MySQL (MariaDB), HubSpot (forms & chatbot), AWS (CloudFront Functions, Route 53))",
    project2Title: "Web Development",
    project2Desc: "5+ years of freelance website creation to ongoing maintenance for individual clients ranging from local governments to small businesses (Tech stack: HTML, CSS, JavaScript, React, TypeScript, Next.js)",
    project3Title: "Site Operation & Maintenance",
    project3Desc: "Experienced in operating and maintaining various CMS platforms including WordPress, HubSpot, and STUDIO. Responsible for bug fixes, feature implementation, server management, and creating setup and deployment documentation.",
    contactText: "Tokyo",
    skillsTitle: "Skills",
    skill1Title: "Frontend",
    skill1Item1: "HTML / CSS / JavaScript (6 years)",
    skill1Item2: "React / TypeScript / Next.js (1 year)",
    skill1Item3: "Cypress (E2E testing)",
    
    skill2Title: "Backend",
    skill2Item1: "Ruby (1 year)",
    skill2Item2: "Database operations (MySQL / MariaDB)",
    skill2Item3: "API integration & implementation",
    
    skill3Title: "SRE / Infrastructure",
    skill3Item1: "DNS design & management",
    skill3Item2: "Server setup & operations",
    skill3Item3: "Cloud Functions (automation tasks)",
    skill3Link: "https://sivasq.siva-s.com/posts/the-best-challenger",
    passionTitle: "Passion Project",
    passionText: "I've spent nearly 10 years volunteering in special education, working with over 10 schools across Japan. During that time, I’ve taught and created learning materials for more than 1,000 students. I'm currently developing an interactive website based on an original children’s book, tailored for diverse learning needs."
  },
};
