// lang.js
export const translations = {
  jp: {
    aboutTitle: "私について",
    aboutText:
      "東京在住のバイリンガルWebデザイナー／デベロッパー。ホームページ制作経験は5年。几帳面なISTJ気質に、牡羊座ならではのひらめきをプラスして、スマートで構造的、かつクリエイティブなWeb体験を創り上げます。",
    projectsTitle: "プロジェクト",
    project1Title: "プロジェクト1",
    project1Desc: "1説明",
    project2Title: "プロジェクト2",
    project2Desc: "2説明",
    project3Title: "プロジェクト3",
    project3Desc: "3説明",
    contactText: "東京都",
    skillsTitle: "スキル",
    skill1Title: "フロントエンド",
    skill1Item1: "React",
    skill1Item2: "TypeScript",
    skill1Item3: "CSSアニメーション",
    skill2Title: "バックエンド",
    skill2Item1: "Node.js",
    skill2Item2: "Express",
    skill2Item3: "MongoDB",
    skill3Title: "ツール",
    skill3Item1: "Git",
    skill3Item2: "Figma",
    skill3Item3: "Webpack",
  },
  en: {
    aboutTitle: "About Me",
    aboutText:
      "Bilingual web designer/developer based in Tokyo, Japan. 5 years of engineering experience. ISTJ focus, Aries flair — I build smart, structured, creative web experiences.",
    projectsTitle: "Projects",
    project1Title: "Project1",
    project1Desc: "Elegant and fast personal site",
    project2Title: "Project2",
    project2Desc: "2Desc",
    project3Title: "Project 3",
    project3Desc: "3Desc",
    contactText: "Tokyo",
    skillsTitle: "Skills",
    skill1Title: "Frontend",
    skill1Item1: "React",
    skill1Item2: "TypeScript",
    skill1Item3: "CSS Animations",
    skill2Title: "Backend",
    skill2Item1: "Node.js",
    skill2Item2: "Express",
    skill2Item3: "MongoDB",
    skill3Title: "Tools",
    skill3Item1: "Git",
    skill3Item2: "Figma",
    skill3Item3: "Webpack",
  },
};
